version: '3.0'

services:
   rego:
      build: rego/.
      command: npm run dev
      restart: always
      ports:
         - 8080:8080
      networks:
         - mmt-dmz
         - proxy
      volumes:
         - ./rego/src/:/usr/src/client
         - ./rego/tests/:/usr/src/tests
         - ./rego/coverage/:/usr/src/coverage
      environment:
         NODE_ENV: ${MMT19_ENV}
   admin:
      build: admin/.
      command: npm run dev
      restart: always
      ports:
         - 8081:8081
      networks:
         - mmt-dmz
         - proxy
      volumes:
         - ./admin/src/:/usr/src/client
         - ./admin/tests/:/usr/src/tests
         - ./admin/coverage/:/usr/src/coverage
      environment:
         NODE_ENV: ${MMT19_ENV}
   rego-api:
      build: rego-api/.
      command: cargo watch -d0.1 -x run
      ports:
         - 8082:8000
      networks:
         - mmt-dmz
         - proxy
      volumes:
         - ./rego-api/src:/e/src
         - ./rego-api/Cargo.toml:/e/Cargo.toml
         - ./rego-api/Cargo.lock:/e/Cargo.lock
         - ./rego-api/Rocket.toml:/e/Rocket.toml
         - ./rego-api/templates:/e/templates
         - regoapitarget:/e/target
         - regoapicargoregistry:/usr/local/cargo/registry
      environment:
         ENVIRONMENT: development 
         MAILGUN_HELLO: ${MMT20_MAILGUN_HELLO}
         MAILGUN_SERVER: ${MMT20_MAILGUN_SERVER}
         MAILGUN_USER: ${MMT20_MAILGUN_USER}
         MAILGUN_PASS: ${MMT20_MAILGUN_PASS}
         EMAIL_RETURN: ${MMT20_EMAIL_RETURN}
         STRIPE_API_KEY: ${MMT20_STRIPE_API_KEY}
   admin-api:
      build: rego-api/.
      command: cargo watch -d0.1 -x run
      ports:
         - 8083:8000
      networks:
         - mmt-dmz
         - proxy
      volumes:
         - ./admin-api/src:/e/src
         - ./admin-api/Cargo.toml:/e/Cargo.toml
         - ./admin-api/Cargo.lock:/e/Cargo.lock
         - ./admin-api/Rocket.toml:/e/Rocket.toml
         - ./admin-api/templates:/e/templates
         - adminapitarget:/e/target
         - adminapicargoregistry:/usr/local/cargo/registry
      environment:
         ENVIRONMENT: development 
         MAILGUN_HELLO: ${MMT20_MAILGUN_HELLO}
         MAILGUN_SERVER: ${MMT20_MAILGUN_SERVER}
         MAILGUN_USER: ${MMT20_MAILGUN_USER}
         MAILGUN_PASS: ${MMT20_MAILGUN_PASS}
         EMAIL_RETURN: ${MMT20_EMAIL_RETURN}
         SENTRY_ADDRESS: ${MMT20_SENTRY_ADMIN_API}
         STRIPE_API_KEY: ${MMT20_STRIPE_API_KEY}
   nginx:
      build: ./nginx
      restart: always
      # ports:
      #    - "8080:80"
      networks:
         - proxy
      links:
         - rego
         - admin
   db:
      image: mongo
      restart: always
      ports:
         - "27017:27017"
      networks:
         - mmt-dmz
      volumes:
         - /Users/grant/mongodb_data:/data/db

networks:
   default:
      driver: bridge
   mmt-dmz:
      external:
         name: mmt-dmz
   proxy:
      external:
         name: proxy
volumes:
  regoapitarget:
      driver: local
  regoapicargoregistry:
      driver: local
  adminapitarget:
      driver: local
  adminapicargoregistry:
      driver: local
