fn_single_line = true
hard_tabs = true
match_block_trailing_comma = true
merge_imports = true
space_before_colon = true
struct_field_align_threshold = 20
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true
