# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-backend:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          RAILS_ENV: test
          DB_URL: 127.0.0.1
          DB_TEST_USER: root
          DB_TEST_NAME: mmt_backend-test
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    working_directory: ~/mmt/backend
    steps:
      - checkout:
          path: ~/mmt

      - restore_cache:
          keys:
            - mmt-backend-bundle-v8-{{ checksum "Gemfile.lock" }}
            - mmt-backend-bundle-v8-
  
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path ~/mmt/backend/bundle || bundle install --path ~/mmt/backend/bundle

        # Store bundle cache for Ruby dependencies
      - save_cache:
          key: mmt-backend-bundle-v8-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/mmt/backend/bundle

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
  
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://root@localhost:5432/mmt_test"
  
      - run:
          name: Test Empty Rails API
          command: |
            bundle exec rails test
          environment:
            DISABLE_SPRING: 1
            DATABASE_URL: "postgres://root@localhost:5432/mmt_test"
  
      - store_test_results:
          path: /tmp/test-results

  test-rego:
    docker:
      - image: circleci/node:8.9.1
        environment:
          NODE_ENV: test
    working_directory: ~/mmt/rego
    steps:
      - checkout:
          path: ~/mmt

      - restore_cache:
          keys:
            - mmt-rego-modules-v1-{{ checksum "package.json" }}
            - mmt-rego-modules-v1-
  
      - run: # Install Ruby dependencies
          name: NPM Install
          command: npm install

        # Store bundle cache for Ruby dependencies
      - save_cache:
          key: mmt-rego-modules-v1-{{ checksum "package.json" }}
          paths:
            - ~/mmt/rego/node_modules

      - run:
          name: Test Empty Node React
          command: |
            npm test

      - run:
          name: Check Code Coverage is 100%
          command: |
            npm run check-coverage
  
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml

  test-admin:
    docker:
      - image: circleci/node:8.9.1
        environment:
          NODE_ENV: test
    working_directory: ~/mmt/admin
    steps:
      - checkout:
          path: ~/mmt

      - restore_cache:
          keys:
            - mmt-admin-modules-v1-{{ checksum "package.json" }}
            - mmt-admin-modules-v1-
  
      - run: # Install Ruby dependencies
          name: NPM Install
          command: npm install

        # Store bundle cache for Ruby dependencies
      - save_cache:
          key: mmt-admin-modules-v1-{{ checksum "package.json" }}
          paths:
            - ~/mmt/admin/node_modules

      - run:
          name: Test Empty Node React
          command: |
            npm test

      - run:
          name: Check Code Coverage is 100%
          command: |
            npm run check-coverage
  
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test-results.xml
          prefix: tests
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: coverage
          prefix: coverage
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test-results.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-backend
      - test-rego
      - test-admin
      # - test:
      #   requires:
      #     - build
