[package]
name = "admin-api"
version = "0.1.0"
authors = ["Grant Perry <grant42perry@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"
name = "libmmtapi"

[[bin]]
path = "src/bin/main.rs"
name = "mmtapi"

[dependencies]
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "mongodb_pool"] }
bson = "0.14.0"
mongodb = "0.3"
juniper = "0.14.2"
juniper_rocket = "0.5"
rocket_cors = "0.5.1"
stripe-rust = { version = "0.11.*", default-features = true }
rand = "0.7"
lettre = { git = "https://github.com/lettre/lettre" }
email = { version = "^0.0.20" }
askama = "0.8"
